### ISSUE TITLE
Website Link Issue

### ISSUE THREAD

**Issue by Moyu-moyuing** [refuel-ai/refuel-docs#10]
# Description:
I am a regular visitor to the refuel.ai website, particularly for reading technical reports. Today, while reading one of the technical reports, I noticed an issue with a link and would like to report it for correction. The specific issue is as follows:

## Issue Description:
On the page https://www.refuel.ai/blog-posts/llm-labeling-technical-report, I observed that a certain link on the page appears to have a problem. When I clicked on this particular link, I expected it to take me to another page, but it did not correctly redirect, or it displayed an error message.

## Link Information:
Option: the research of PaLM2
![image](https://github.com/refuel-ai/refuel-docs/assets/68681179/b6019e64-1b31-4fd2-a21e-6befdbdf31ea)
![image](https://github.com/refuel-ai/refuel-docs/assets/68681179/219355b2-a6dd-42d4-96aa-938b6fec7b04)

## Expected Outcome:
I expected that when I click on the link, it should correctly redirect to the intended page or resource.

## Actual Outcome:
Currently, when I click on the link, it does not work as expected, which may lead to user confusion and accessibility issues.

## Additional Information:
It's quite evident that the link should be "https://arxiv.org/pdf/2305.10403.pdf" instead of "http://https//arxiv.org/pdf/2305.10403.pdf"？

**Comment by rishabh-bhargava** [comment]
Thanks for flagging this @Moyu-moyuing -- this should be fixed now!
